mutation  updatePost($input: UpdatePostInput!){
    updatePost(updatePostInput:$input){
    createdAt
    updatedAt
    likes
    id
    published
    subject
    ownerId
    audio{
        id
      url
      file_name
      ownerId
    }
    video{
      id
      url
      file_name
      ownerId
    }
    text
    image{
       id
      url
      file_name
      ownerId
    }
    likes
     owner{
        id
        username
        avatar{
             id
      url
      file_name
        }
    }
    }
  }
