export enum FOLDERS {
  IMAGES = 'images',
  VIDEOS = 'videos',
  AUDIOS = 'audios',
  AVATAR = 'avatar',
  COVER = 'cover',
  POST_IMAGE = 'post_image',
  POST_VIDEO = 'post_video',
  POST_AUDIO = 'post_audio',
  AUDIO_F_COMMENT_F_PHOTO = 'audio_f_comment_f_photo',
  AUDIO_F_COMMENT_F_POST = 'audio_f_comment_f_post',
  AUDIO_F_COMMENT_F_VIDEO = 'audio_f_comment_f_video',
  VIDEO_F_COMMENT_F_PHOTO = 'video_f_comment_f_photo',
  VIDEO_F_COMMENT_F_POST = 'video_f_comment_f_post',
  VIDEO_F_COMMENT_F_VIDEO = 'video_f_comment_f_video',
  IMAGE_F_COMMENT_F_PHOTO = 'image_f_comment_f_photo',
  IMAGE_F_COMMENT_F_POST = 'image_f_comment_f_post',
  IMAGE_F_COMMENT_F_VIDEO = 'image_f_comment_f_video',
}

export type AvatarOrCover = FOLDERS.AVATAR | FOLDERS.COVER

export type GaleryFolderT = FOLDERS.IMAGES | FOLDERS.VIDEOS | FOLDERS.AUDIOS
export type PostFolderT =
  | FOLDERS.POST_IMAGE
  | FOLDERS.POST_VIDEO
  | FOLDERS.POST_AUDIO
export type AllCommentFolderT =
  | FOLDERS.IMAGE_F_COMMENT_F_PHOTO
  | FOLDERS.IMAGE_F_COMMENT_F_POST
  | FOLDERS.IMAGE_F_COMMENT_F_VIDEO
  | FOLDERS.VIDEO_F_COMMENT_F_PHOTO
  | FOLDERS.VIDEO_F_COMMENT_F_POST
  | FOLDERS.VIDEO_F_COMMENT_F_VIDEO
  | FOLDERS.AUDIO_F_COMMENT_F_PHOTO
  | FOLDERS.AUDIO_F_COMMENT_F_POST
  | FOLDERS.AUDIO_F_COMMENT_F_VIDEO

export type Image_F_CommentFolderT =
  | FOLDERS.IMAGE_F_COMMENT_F_PHOTO
  | FOLDERS.IMAGE_F_COMMENT_F_POST
  | FOLDERS.IMAGE_F_COMMENT_F_VIDEO

export type Video_F_CommentFolderT =
  | FOLDERS.VIDEO_F_COMMENT_F_PHOTO
  | FOLDERS.VIDEO_F_COMMENT_F_POST
  | FOLDERS.VIDEO_F_COMMENT_F_VIDEO

export type Audio_F_CommentFolderT =
  | FOLDERS.AUDIO_F_COMMENT_F_PHOTO
  | FOLDERS.AUDIO_F_COMMENT_F_POST
  | FOLDERS.AUDIO_F_COMMENT_F_VIDEO

export type FOR_PHOTO_T =
  | FOLDERS.IMAGE_F_COMMENT_F_PHOTO
  | FOLDERS.VIDEO_F_COMMENT_F_PHOTO
  | FOLDERS.AUDIO_F_COMMENT_F_PHOTO

export type FOR_VIDEO_T =
  | FOLDERS.IMAGE_F_COMMENT_F_VIDEO
  | FOLDERS.VIDEO_F_COMMENT_F_VIDEO
  | FOLDERS.AUDIO_F_COMMENT_F_VIDEO
export type FOR_POST_T =
  | FOLDERS.AUDIO_F_COMMENT_F_POST
  | FOLDERS.IMAGE_F_COMMENT_F_POST
  | FOLDERS.VIDEO_F_COMMENT_F_POST
